#!/bin/bash



TESTS="1 2 5 14 42 132 429 1430 55 02 03 04 05 06"

for i in $TESTS
do
	echo "compiling test $i"
	g++ -std=c++11 test$i.cpp uthreads.h uthreads.cpp Thread.h Thread.cpp -o test$i
done



